### ISSUE TITLE
Feature & Todo

### ISSUE THREAD

**Issue by rimsila** [next-dev-team/nextjs-next-boilerplate#1]
- **CURRENT FEATURE**
- [x] Demo 
- [x] Atom Design
- [x] typescript 
- [x] React 17 
- [x] i18n
- [x] dark mode
- [x] state management - Hookstate (proxy base)
- [x] Apollo GraphQl
- [x] useRequest (Rest)
- [x] Lint, Prettier, husky, commit lint
- [x] Tailwind Css 3
- [x] Tailwind Component (form, button...)
- [x] SSR SEO NextJs 12
- [x] Layout (Container, Section...)
- [x] import on demand with babel-import
- [ ] Deployment

-  **TODO**
- [x] common Utils
- [ ] Storybook or dumijs
- [ ] Analyst event
- [ ] Unit test and E2E
- [x] Generator (component,route, store...)
- [ ] Docker
- [ ] Auth
- [ ] Firebase
- [ ] Socket
- [ ] PWA
- [ ] AMP
- [ ] Performance Analyst 
- [ ] Electron
- [ ] Redux 
- [ ] Mobx
- [ ] Antd Design 
- [ ] Facebook Plugin
- [ ] Chat 
- [ ] multi-tenant dev,qa,uat
